import java.util.ArrayList;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class ProjeTable extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form Proje
     */
    public ProjeTable() {
        initComponents();
        populateTable();
    }
    public void populateTable(){
        model = (DefaultTableModel)tblProjeler.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Proje> projeler = getProjeler();
            for(Proje proje: projeler){
                Object[] row = {proje.getId(), proje.getAd(),
                    proje.getBaslangicTarihi(), proje.getBitisTarihi()};
                model.addRow(row);
            }
            tblProjeler.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tblProjeler.rowAtPoint(evt.getPoint());
                int col = tblProjeler.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {
                    
                    int selectedId =(int) model.getValueAt(row, 0);
                    
                    GorevTable gorevTable =new GorevTable(selectedId);
                    gorevTable.setVisible(true);
                }
            }
        });
           
        } catch (SQLException ex) {
            
        } 
    }
    public ArrayList<Proje> getProjeler() throws SQLException{
        Connection connection=null;
        DbHelper dbHelper=new DbHelper();
        Statement statement=null;
        ResultSet resultSet;
        ArrayList<Proje> projeler=null;
        
        try{
            connection = dbHelper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from Proje");
            projeler = new ArrayList<Proje>();
            while(resultSet.next()){
                projeler.add(new Proje(
                        
                        resultSet.getInt("prjId"),
                        resultSet.getString("prjAdı"),
                        resultSet.getDate("prjBasTar"),
                        resultSet.getDate("prjBitTar")
                ));
            }
        }catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
            
        }finally{
            statement.close();
            connection.close();
        }
        return projeler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjeler = new javax.swing.JTable();
        lblProjeler = new javax.swing.JLabel();
        btnEkle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBasla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBitis = new javax.swing.JTextField();
        btnCalisanlar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProjeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Ad", "Başlangıç Tarihi", "Bitiş Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProjeler);
        if (tblProjeler.getColumnModel().getColumnCount() > 0) {
            tblProjeler.getColumnModel().getColumn(0).setResizable(false);
            tblProjeler.getColumnModel().getColumn(1).setResizable(false);
            tblProjeler.getColumnModel().getColumn(2).setResizable(false);
            tblProjeler.getColumnModel().getColumn(3).setResizable(false);
        }

        lblProjeler.setText("     Projeler");

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        jLabel2.setText("Başlangıç Tarihi");

        jLabel3.setText("Ad");

        jLabel4.setText("Bitiş Tarihi");

        btnCalisanlar.setText("Çalışanlar");
        btnCalisanlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalisanlarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(txtBasla, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(txtBitis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(btnEkle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblProjeler, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalisanlar)
                        .addGap(89, 89, 89))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjeler)
                    .addComponent(btnCalisanlar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBasla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtBitis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnEkle)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        Connection connection=null;
        DbHelper dbHelper=new DbHelper();
        PreparedStatement statement =null;
        try{
            connection = dbHelper.getConnection();
            String sql = "insert into proje (prjAdı,prjBasTar,prjBitTar) values(?,?,?)";
            statement = connection.prepareStatement(sql);
        
            statement.setString(1, txtAd.getText());
            statement.setString(2, txtBasla.getText());
            statement.setString(3, txtBitis.getText());
            
            int result = statement.executeUpdate();
            txtAd.setText("");
            txtBasla.setText("");
            txtBitis.setText("");
            populateTable();
            
        }catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
            
        }finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
                
            }
        }
                                          
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnCalisanlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalisanlarActionPerformed
        CalisanTable calisanTable =new CalisanTable();
        calisanTable.setVisible(true);
    }//GEN-LAST:event_btnCalisanlarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalisanlar;
    private javax.swing.JButton btnEkle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProjeler;
    private javax.swing.JTable tblProjeler;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtBasla;
    private javax.swing.JTextField txtBitis;
    // End of variables declaration//GEN-END:variables
}
